- hosts: demo
  gather_facts: no
  tasks:
    - name: Get users
      ansible.builtin.shell:
        cmd: >
          getent passwd | awk -F: '$7 !~ /(false|nologin)$/' | grep -v '^$' | awk -F":" '{ print $1 }'
      register: users

    - name: Gather posix account
      ansible.builtin.shell: |
        for user in {{ users.stdout_lines | join(" ") }}; do
          k=$(last --time-format iso $user -1 | head -1 | grep -v ^$ | awk '{ print $0 }')
          if [ -n "$k" ]; then
            echo $k
          fi
        done
      register: last_login

    - name: Get user groups
      ansible.builtin.shell: |
        for user in {{ users.stdout_lines | join(" ") }}; do
          echo "$(groups $user)"
        done
      register: user_groups

    - name: Get sudo permissions
      ansible.builtin.shell: |
        for user in {{ users.stdout_lines | join(" ") }}; do
          echo "$user: $(grep "^$user " /etc/sudoers | tr '\n' ';' || echo '')"
        done
      register: user_sudo

    - name: Get authorized keys
      ansible.builtin.shell: |
        for user in {{ users.stdout_lines | join(" ") }}; do
          home=$(getent passwd $user | cut -d: -f6)
          echo -n "$user:"
          if [[ -f ${home}/.ssh/authorized_keys ]]; then
            cat ${home}/.ssh/authorized_keys | tr '\n' ';'
            echo
          fi
        done
      register: user_authorized

    - name: Display user groups
      ansible.builtin.debug:
        var: user_groups.stdout_lines

    - name: Display sudo permissions
      ansible.builtin.debug:
        var: user_sudo.stdout_lines

    - name: Display authorized keys
      ansible.builtin.debug:
        var: user_authorized.stdout_lines

    - name: Display last login
      ansible.builtin.debug:
        var: last_login.stdout_lines

    - name: Define info by set_fact
      ansible.builtin.set_fact:
        var: last_login.stdout_lines
